name: Release Plugin

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload Plugin Jar
        uses: actions/upload-artifact@v4
        with:
          name: Plugin Jar
          path: target/<artifactId>-<version>.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Plugin Jar
        uses: actions/download-artifact@v4
        with:
          name: Plugin Jar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/<artifactId>-<version>.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
